### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by LuluW8071** [Bootcamp-Portfolio/Rojen-Maharjan#1]
Hi Rojen,

I hope this message finds you well. I wanted to take a moment to review your portfolio and provide you with some **constructive feedback** on your web design development using HTML and CSS. Firstly, let me say that you're definitely on the right track, but try to add your own creativity when using others stock portfolio.

I noticed that your portfolio showcases many lorem ipsum on **services** and as well as experience. Also **never add your private phone no** on the portfolio. Other than that keep up the excellent work, and I'm excited to see how you progress in your web design journey!

If you need any further assistance or feedback, feel free to reach out.

Best regards,  
Shashin

_____
![Screenshot 2023-07-21 194859](https://github.com/Bootcamp-Portfolio/Rojen-Maharjan/assets/107304848/55d32445-e67a-491b-879b-73187245e859)

**Comment by Zen-XD** [comment]
Hello dai,
I have taken into consideration your comments about my portfolio and have amended it to the best of my abilities.
I hope you will take the time to review it again.
Thank you.

**Comment by LuluW8071** [comment]
> 

Great to hear that you've ammended the portfolio! Your navigation system is clear and user-friendly, making it easy for visitors to explore different sections. I particularly liked the minimalist design, which really highlights your creativity and attention to detail.

Keep up the fantastic work, and I have no doubt that your talent and passion for web design will lead you to great opportunities in the future.
